### ISSUE TITLE
the trait `ResponseError` is not implemented for `jammdb::Error`

### ISSUE THREAD

**Issue by ArunGust** [pjtatlow/jammdb#5]
Hi,

I got the below error for integration with actix web app.  Anyway, idea how to resolve this?

let mut tx = _jdb.tx(true)?;
    |                                   ^ the trait `ResponseError` is not implemented for `jammdb::Error`

**Comment by pjtatlow** [comment]
Hi @ArunGust

Your problem is that you are using the `?` operator, which returns the error from the `tx` method, which if of type `jammdb::Error`. But I'm assuming the function you're using this in returns an error type of `actix_web::ResponseError`, which isn't satisfied by a `jammdb::Error`. 

You should look into using something like [`map_err`](https://doc.rust-lang.org/std/result/enum.Result.html#method.map_err) to convert the `jammdb::Error` into something that satisfies the `ResponseError` trait, or create another type that implements `From<jammdb::Error>` as well as `actix_web::ResponseError` and return that instead!

Hopefully that helps!

**Comment by ArunGust** [comment]
Thank you @pjtatlow 

I tried to clone and pass-through 

    let jdb = jammdb::DB::open("../jammdb").unwrap();
    HttpServer::new(move || {
        App::new()
            .data(jdb.clone())

async fn fn_inituserdb(req: HttpRequest, _jdb: Data<jammdb::DB>) ->Result<String, Error> {
33 |             let _tx = _jdb.tx(true).borrow_mut().as_ref().map_err(|e| actix_web::http::StatusCode::BAD_REQUEST);
    |                       **^^^^ cannot borrow as mutable**

**Comment by pjtatlow** [comment]
Have you tried getting rid of the `borrow_mut` and `as_ref`?

**Comment by ArunGust** [comment]
Yes, below error popup

cannot borrow data in an `Arc` as mutable
trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Arc<DB>`rustcE0596
[E0596] cannot borrow data in an `Arc` as mutable. 
[Note] cannot borrow as mutable
[E0596] cannot borrow data in an `Arc` as mutable. 
[Note] cannot borrow as mutable
[E0596] cannot borrow data in an `Arc` as mutable. 
[Note] cannot borrow as mutable

**Comment by pjtatlow** [comment]
Hmm, looks like `actix_web` wraps anything in `Data` in an `Arc`. Let me take a look and see what I can come up with.

**Comment by ArunGust** [comment]
Thank you
